### PR TITLE
artery aorta eqtl

### PR DESCRIPTION
**Pull request by ypar**

### CODE REVIEW

**Comment by cgreene** [comment]
FYI your and @dongbohu's checks aren't working: https://github.com/greenelab/cimr-d/pull/39/checks

My impression was that you were setting up testing of each file before you had to merge it.

**Comment by dongbohu** [comment]
@cgreene: The check is working but it doesn't show in the URL that you posted above. I don't know why.

**Comment by dongbohu** [comment]
Here is the check: https://circleci.com/gh/greenelab/cimr-d/329

**Comment by cgreene** [comment]
It looks like the branch was not set up as protected, so it wasn't enforcing the checks. Things are now set so there must be one PR review and the `crunch` must pass. Hopefully this will get the status checks working.

**Comment by ypar** [comment]
Cool beans. Thanks for spotting!

**Pull request merged**
