### PR TITLE
Use cimr-d_catalog.txt to avoid downloading duplicate files

### PR DESCRIPTION
**Pull request by dongbohu**
Here is a summary of this PR:
- Use `cimr-d_catalog.txt` to check input yaml file's md5sum; If the file has been processed previously, report an error;
- Commit `cimr-d_catalog.txt` at the end of deployment;
- Remove "git lfs" commands that were run inside `cimr-d` repo, because they are not needed any more.

### CODE REVIEW

**Comment by dongbohu** [comment]
@ypar: I merged the changes in #22 to this PR and closed #22. I keep git-lfs installation in cimr because you said that `cimr` still uses git-lfs, is that right?

**Comment by ypar** [comment]
My latest updates to cimr removed git-lfs requirements.

**Comment by dongbohu** [comment]
I have removed `git-lfs` from `cimr` too.

**Comment by dongbohu** [comment]
Let me know if you have any other comments.

**Comment by ypar** [comment]
PR_NUMBER in s3 seems to follow cimr PR order rather than cimr-d's

**Review by ypar — APPROVED** [review]
lntm

**Pull request merged**
